### ISSUE TITLE
Glitches in UI

### ISSUE THREAD

**Issue by dalini** [SecurityRAT/SecurityRAT#23]
We experience a lot of error messages - related to non availability of elasticsearch. So especially editing entities is possible but there are always errors shown related to elasticsearch (nodes not available) while the edit, new item or delete itself worked.

The change is not visible in the UI until the page is reloaded and the date fetched newly from database. This might be due to the error shown... action itself works but this is a little inconvenient.

Setup: prod + Form auth

**Comment by dkefer** [comment]
Thanks for the issue! Can you please provide the "spring" part of your application-prod.yml (without any credentials)?

**Comment by dalini** [comment]
the data: section had been removed, but it makes no difference it is in or not - the system behaves the same - tries to talk to elasticsearch

```
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes: localhost:9200
```

```
spring:
    profiles:
        active: prod
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/securityrat?useUnicode=true&characterEncoding=utf8  #edit according to the DB server and DB name
        databaseName: xxx
        serverName: localhost
        username: xxx #change to your db user
        password: xxx
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

    thymeleaf:
        mode: XHTML
        cache: true
```
